FROM node:18-bullseye

RUN npm install -g nx @nrwl/cli

COPY --chown=node:node . /usr/src/app

WORKDIR /usr/src/app
RUN rm -rf node_modules
RUN npm install --force --loglevel verbose

CMD ["sh", "-c", "npm run start:api"]
